name: action

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - name: Checkout  # 将代码拉到虚拟机
#      uses: actions/checkout@v2.3.1
#
#    - name: docker-build-images
#      run: |
#        cd devops/front-end/
#        docker build -t evegarden/todo-client:latest .
#        cd ..
#        cd server/
#        docker build -t evegarden/todo-server:latest .
#        docker login -u ${{secrets.USERNAME_DOCKER}} -p ${{secrets.PASSWORD_DOCKER}}
#        docker push evegarden/todo-client:latest
#        docker push evegarden/todo-server:latest

    - name: composeFile
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
      with:
          # tag_name: docker-compose-latest
          tag: docker-compose
          # release_name: docker-compose
          name: docker-compose
          # commitish: docker-compose
          commit: docker-compose
          # allowUpdates: true

    # - name: deploy
    #   uses: appleboy/ssh-action@v1.0.0
    #   with: 
    #     host: ${{secrets.HOST}}
    #     username:  ${{secrets.USERNAME}}
    #     password: ${{secrets.PASSWORD}}
    #     script: |
    #       rm -rf  /home/github-action/*
    #       cd /home/github-action
    #       wget https://github.com/wutongyulu/interview/archive/refs/tags/docker-compose.tar.gz
    #       tar -zxvf docker-compose.tar.gz
    #       cd /home/github-action/interview-docker-compose/devops
    #       docker login -u ${{secrets.USERNAME_DOCKER}} -p ${{secrets.PASSWORD_DOCKER}}
    #       docker-compose -f docker-compose.yaml up -d
          
