name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: appleboy/ssh-action@v1.0.0
    - name: deploy
      with: 
        host: ${{HOST}}
        username:  ${{USERNAME}}
        password: ${{PASSWORD}}
        script: |
          cd /home/github-action
          
