name: action

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  
      uses: actions/checkout@v2.3.1

    # - name: docker-build-images
    #   run: |
    #     cd devops/front-end/
    #     docker build -t evegarden/todo-client:latest .
    #     cd ..
    #     cd server/
    #     docker build -t evegarden/todo-server:latest .
    #     docker login -u ${{secrets.USERNAME_DOCKER}} -p ${{secrets.PASSWORD_DOCKER}}
    #     docker push evegarden/todo-client:latest
    #     docker push evegarden/todo-server:latest
    - name: tar docker-compose-config
      run: |
        cd devops
        tar -cvzf docker-compose.tar.gz docker-compose.yaml env/
        
    - name: composeFile
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
      with:
          token: ${{secrets.TOKEN}}
          tag: main-docker-compose
          allowUpdates: true
          replacesArtifacts: true
          removeArtifacts: true
          artifacts: "devops/docker-compose.tar.gz,devops/test/test.ts"
       

    # - name: deploy
    #   uses: appleboy/ssh-action@v1.0.0
    #   with: 
    #     host: ${{secrets.HOST}}
    #     username:  ${{secrets.USERNAME}}
    #     password: ${{secrets.PASSWORD}}
    #     script: |
    #       rm -rf  /home/github-action/*
    #       cd /home/github-action
    #       wget https://github.com/wutongyulu/interview/releases/download/main-docker-compose/docker-compose.tar.gz
    #       tar -zxvf docker-compose.tar.gz         
    #       docker login -u ${{secrets.USERNAME_DOCKER}} -p ${{secrets.PASSWORD_DOCKER}}
    #       docker-compose down -v
    #       docker-compose -f docker-compose.yaml up -d
    - name: test
      uses: actions/setup-node@v3
      with:
        node-version: 18
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        pwd
        ls
        cd devops/tests
        npx playwright test 
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
